safe: true
lsi: false
pygments: true
download:
    version: 0.15.0
    date: "June 10th, 2013"

doc_boxes:
  - box: Getting Started
    items:
      - title: Welcome
        link: index
      - title: Installation
        link: installation
      - title: Directory Structure
        link: structure
      - title: Basic Usage
        link: usage
      - title: Configuration
        link: configuration
  - box: Guides
    items:
      - title: Controllers
        link: controllers
      - title: Bindings
        link: bindings
      - title: Views
        link: views
      - title: Models
        link: models
      - title: Testing
        link: testing

docs:
  - title: Batman.Object
    link: object
