safe: true
lsi: false
pygments: true
download:
    version: 0.15.0
    date: "June 10th, 2013"

doc_boxes:
  - box: Developer Guide
    items:
      - title: Getting Started
        link: index
      - title: Architecture
        link: architecture
      - title: App Structure
        link: structure
      - title: Installation
        link: installation
      - title: Configuration
        link: configuration
      - title: Controllers
        link: controllers
      - title: Models
        link: models
      - title: Bindings
        link: bindings
      - title: Views
        link: views
      - title: Testing
        link: testing

#= api_index
